info:
  description: A service running a REST API that serves accessioned metadata files
    by study ID
  title: Workshop Service
  version: 1.0.0
openapi: 3.1.0
paths:
  /health:
    get:
      description: Used to test if this service is alive
      operationId: health_health_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: health
servers:
- url: ''
