[project]
name = "ws1"
version = "1.0.0"
description = "Workshop Service 1 - a service to teach about services"
dependencies = [
    "typer >= 0.19.1",
    "ghga-service-commons[api] >= 5.0",
    "ghga-event-schemas >= 10.0",
    "hexkit[akafka,mongodb] >= 7.0",
]

[project.urls]
Repository = "https://github.com/ghga-de/workshop-service-1"

[project.scripts]
ws1 = "ws1.__main__:run"
